import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Profile from "../components/Profile";
import Bible from "../components/Bible";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <main className="relative w-full max-w-container mx-auto mt-[70px] lg:grid lg:grid-cols-[300px_1fr] lg:gap-6">
        <div></div>
        <Profile />
        <Bible />
      </main>
    </>
  );
};

export default Home;
